# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dfnbdevtest',
                'doc_host': 'https://DavidFarrell.github.io',
                'git_url': 'https://github.com/DavidFarrell/dfnbdevtest',
                'lib_path': 'dfnbdevtest'},
  'syms': {'dfnbdevtest.core': {'dfnbdevtest.core.foo': ('core.html#foo', 'dfnbdevtest/core.py')}}}
